# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 07:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('H', 'Healthy'), ('R', 'Regenerating')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('license_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_license_number', message='License number must consist of three capital letters followed by seven digits', regex='^[A-Z]{3}[0-9]{7}$')])),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokecenter.Trainer'),
        ),
    ]
