# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, unique=True)),
                ('tradeEvolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.PokemonType')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Trainer'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.PokemonType'),
        ),
    ]
