# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontype',
            name='tradeEvolution',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trading.PokemonType'),
        ),
    ]
