# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20170616_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='district',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.District'),
        ),
        migrations.AlterField(
            model_name='results',
            name='municipality',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Municipality'),
        ),
        migrations.AlterField(
            model_name='results',
            name='place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Place'),
        ),
        migrations.AlterField(
            model_name='results',
            name='voivodeship',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Voivodeship'),
        ),
    ]
