# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20170616_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'results'},
        ),
    ]
