# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'municipalities',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('eligible_voters', models.IntegerField()),
                ('issued_ballots', models.IntegerField()),
                ('spoilt_ballots', models.IntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.District')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Candidate')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Place')),
            ],
            options={
                'verbose_name_plural': 'votes',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='voivodeship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Voivodeship'),
        ),
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together=set([('candidate', 'place')]),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('number', 'municipality', 'district')]),
        ),
    ]
