# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_protocolfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='next_protocol_number',
            field=models.IntegerField(default=1),
        ),
    ]
