# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20170419_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
