# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_auto_20170419_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Place',
        ),
    ]
