# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20170419_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='area',
            new_name='place',
        ),
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together=set([('candidate', 'place')]),
        ),
    ]
