# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_auto_20170419_2255'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set([('number', 'municipality', 'district')]),
        ),
    ]
